import { SidebarProvider } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/app-sidebar'
import type { Metadata } from 'next'
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app'
}

export default function DashboardLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <section>
      <SidebarProvider>
        <AppSidebar />
        {children}
      </SidebarProvider>
    </section>
  )
}
